# Site settings
title: Lawrence Pan
email: lawrencefeipan@gmail.com
name: 'lpan.io'
description: "Lawrence Pan's profile and blog"
baseurl: ""
url: "http://lpan.io"
twitter_username: l_pan_
github_username: lpan

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Build settings
markdown: kramdown

permalink: /:title/

# personal config
operation_system: "Fedora"
desktop_environment: "Gnome 3"
