# Site settings
title: Lawrence Pan
email: lawrencefeipan@gmail.com
description: >
  Lawrence Pan's blog
baseurl: ""
url: "http://lpan.github.io"
twitter_username: l_pan_
github_username: lpan

# Build settings
markdown: kramdown

# personal config
operation_system: "Fedora"
desktop_environment: "Gnome 3"
