# Site settings
title: Lawrence Pan
email: lawrencefeipan@gmail.com
description: "Lawrence Pan's profile and blog"
baseurl: ""
url: "http://lpan.io"
twitter_username: l_pan_
github_username: lpan

# Build settings
markdown: kramdown

permalink: /:categories/:title/

# personal config
operation_system: "Fedora"
desktop_environment: "Gnome 3"
